# Generated by Django 4.2 on 2023-04-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0002_departamento_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
    ]
